import { generateId } from './utils.js';

export function createMockReport(category, isInfluencer) {
  return {
    id: generateId(),
    createdAt: new Date().toISOString(),
    category,
    overallRisk: 'high',
    score: 85,
    summary: { violations: 2, risky: 1, passed: 2 },
    isInfluencer,
    issues: [
      {
        id: generateId(),
        claimText: 'Guaranteed to cure acne in 7 days',
        source: 'photo',
        verdict: 'violation',
        severity: 'high',
        ruleId: 'ASCI-H-1',
        ruleName: 'Health Claims Verification',
        ruleText: 'SAMPLE TEXT: All health claims must be backed by clinical evidence. Guarantees of cure are generally prohibited.',
        explanation: 'The ad makes an absolute guarantee ("Guaranteed to cure") and provides a specific timeline without citing clinical proof.',
        suggestedRewrite: 'Helps reduce acne within 7 days based on clinical studies.',
      },
      {
        id: generateId(),
        claimText: 'Caption missing disclosure',
        source: 'caption',
        verdict: 'violation',
        severity: 'high',
        ruleId: 'ASCI-IF-2',
        ruleName: 'Influencer Disclosure',
        ruleText: 'SAMPLE TEXT: Material connections must be disclosed clearly and prominently (e.g., #ad, #sponsored).',
        explanation: 'No clear #ad or #sponsored tag found in the provided caption.',
        suggestedRewrite: 'Add #ad or #sponsored at the beginning of the caption.',
      },
      {
        id: generateId(),
        claimText: 'Visual before/after comparison',
        source: 'video',
        timestampSeconds: 14,
        verdict: 'risky',
        severity: 'medium',
        ruleId: 'ASCI-G-3',
        ruleName: 'Misleading Comparisons',
        ruleText: 'SAMPLE TEXT: Visual comparisons must not mislead consumers regarding the product\'s efficacy.',
        explanation: 'The before/after comparison appears to use different lighting conditions, which may exaggerate the product\'s effect.',
      },
      {
        id: generateId(),
        claimText: 'Clinically proven',
        source: 'photo',
        verdict: 'needs_review',
        severity: 'medium',
        ruleId: 'ASCI-H-4',
        ruleName: 'Scientific Substantiation',
        ruleText: 'SAMPLE TEXT: Claims of "clinically proven" must reference the specific study or evidence.',
        explanation: 'The phrase "clinically proven" is used without a visible citation or asterisk pointing to a disclaimer.',
        suggestedRewrite: 'Add a clear citation to the clinical study at the bottom of the image.',
      },
      {
        id: generateId(),
        claimText: '₹999 Only',
        source: 'photo',
        verdict: 'pass',
        severity: 'low',
        ruleId: 'ASCI-G-7',
        ruleName: 'Price Disclosure',
        ruleText: 'SAMPLE TEXT: Prices must be clearly indicated and not misleading.',
        explanation: 'The price is clearly displayed without hidden fees in the primary text.',
      },
      {
        id: generateId(),
        claimText: 'Brand Logo visible',
        source: 'video',
        timestampSeconds: 2,
        verdict: 'pass',
        severity: 'low',
        ruleId: 'ASCI-G-8',
        ruleName: 'Brand Identification',
        ruleText: 'SAMPLE TEXT: Advertisements should clearly identify the advertiser.',
        explanation: 'The brand logo is visible and legible early in the video.',
      }
    ]
  };
}
